In [1]:
import numpy as np
import pandas as pd
from pycaret.classification import *

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/psdbia/Class-Share/refs/heads/main/data/loan_defaults.csv')
data.head()

  default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [3]:
data['default'].value_counts()

default
No     9667
Yes     333
Name: count, dtype: int64

In [4]:
s = setup(data, target = 'default', session_id = 42, fix_imbalance=True)   #fix_imbalance=True

In [5]:
s.y_transformed.value_counts()

default
0    9667
1    6867
Name: count, dtype: int64

In [ ]:
s.compare_models(sort='MCC')

Initiated  . . . . . . . . . . . . . . . . . .                10:46:40
Status     . . . . . . . . . . . . . . . . . .  Compiling Final Models
Estimator  . . . . . . . . . . . . . . . . . .     Logistic Regression

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [ ]:
lr_mdl = s.create_model('lr')

In [ ]:
lr_mdl

In [ ]:
#tuned_lr_mdl = s.tune_model(lr_mdl)

In [ ]:
evaluate_model(lr_mdl)

In [ ]:
s.plot_model(lr_mdl, plot='confusion_matrix')

In [ ]:
plot_model(lr_mdl, plot='feature')

# Classification Plots

### Confusion Matrix
Visualizes the performance of a classification model by showing the actual vs. predicted classifications.
```python
plot_model(model, plot='confusion_matrix')
```

### AUC (Area Under the Curve)
Plots the ROC curve and calculates the area under it, which helps in evaluating the model's ability to distinguish between classes.
```python
plot_model(model, plot='auc')
```

### Precision-Recall Curve
Shows the trade-off between precision and recall for different threshold values.
```python
plot_model(model, plot='pr')
```

### Feature Importance
Displays the importance of each feature in the model.
```python
plot_model(model, plot='feature')
```

### Learning Curve
Plots the training and validation scores over different training set sizes to show how the model learns over time.
```python
plot_model(model, plot='learning')
```

### Validation Curve
Shows the model's performance over a range of hyperparameter values.
```python
plot_model(model, plot='vc')
```

### Residuals Plot
Visualizes the residuals (differences between actual and predicted values) to assess the model's fit.
```python
plot_model(model, plot='residuals')
```

### Manifold Learning
Uses techniques like t-SNE or UMAP to visualize high-dimensional data in a lower-dimensional space.
```python
plot_model(model, plot='manifold')
```

### Calibration Curve
Plots the predicted probabilities against the actual outcomes to assess the calibration of the model.
```python
plot_model(model, plot='calibration')
```

### Lift Curve
Shows the lift of the model, which is the ratio of the results obtained with and without the model.
```python
plot_model(model, plot='lift')
```

### Gain Chart
Visualizes the cumulative gain of the model.
```python
plot_model(model, plot='gain')
```

### KS Statistic Plot
Plots the Kolmogorov-Smirnov statistic to evaluate the separation between the positive and negative classes.
```python
plot_model(model, plot='ks')
```

### Cumulative Accuracy Profile (CAP)
Shows the cumulative accuracy of the model.
```python
plot_model(model, plot='cap')
```

### Decision Boundary
Visualizes the decision boundaries of the model.
```python
plot_model(model, plot='boundary')
```